name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    steps:
    - name: "Force HTTPS"
      run: git config --global url."https://github".insteadOf ssh://git@github
  ci:
    uses: robvanderleek/repo-meister/.github/workflows/nodejs-yarn.yml@main
